spring:
  application:
    name: autocatalog
  datasource:
    url: jdbc:postgresql://${AC_POSTGRES_HOST:localhost}:${AC_POSTGRES_PORT:5432}/${AC_POSTGRES_DB:autocatalog}
    username: ${AC_POSTGRES_USER:autocatalog}
    password: ${AC_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8180
logging:
  level:
    root: INFO
    live.yurii: DEBUG
