package live.yurii.autocatalog.domain.powerunit;

import java.util.Objects;

/**
 * Shared identity aggregate for all propulsion units.
 * Concrete types (Engine, ElectricMotor, FuelCellStack) reference this via a shared PK.
 *
 * <p>ID is generated by the database (BIGSERIAL), so {@code id} is null until persisted.
 */
public class PowerUnit {

  private PowerUnitId id;
  private PowerUnitType unitType;

  private PowerUnit() {
  }

  /**
   * Creates a new PowerUnit for a given type. ID will be assigned by the database on save.
   */
  public static PowerUnit create(PowerUnitType unitType) {
    var pu = new PowerUnit();
    pu.unitType = Objects.requireNonNull(unitType, "unitType must not be null");
    return pu;
  }

  /**
   * Rebuilds a PowerUnit from persisted state without re-validating.
   * Used exclusively by repository adapters.
   */
  public static PowerUnit reconstitute(PowerUnitId id, PowerUnitType unitType) {
    var pu = new PowerUnit();
    pu.id = id;
    pu.unitType = unitType;
    return pu;
  }

  public PowerUnitId id() {
    return id;
  }

  public PowerUnitType unitType() {
    return unitType;
  }
}
